name: Generate Daily Art

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs at 01:00 UTC, which is 6:30 AM in India (IST) every day
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    #write perms for the repo
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install Pillow

      - name: Run art generator script
        run: python generate_art.py

      - name: Commit and push the new art
        run: |
          git config --global user.name "Generative Art Bot"
          git config --global user.email "bot@example.com"
          git add art/*.png
          # Commit only if there are changes
          git diff --staged --quiet || git commit -m "feat: Create art for $(date +'%Y-%m-%d')"
          git push